# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

locf <- function(x, reverse) {
    .Call('_imputeTS_locf', PACKAGE = 'imputeTS', x, reverse)
}

ma <- function(x, k, weighting) {
    .Call('_imputeTS_ma', PACKAGE = 'imputeTS', x, k, weighting)
}

